import initialPage from "./initial-page";
import homeElements from "./home.js";
import { footerFunc } from "./initial-page";
import menuPage from "./menu.js";
import "./home.css";
import "./menu.css";
initialPage();
// homeElements();
menuPage();
footerFunc();
